### ISSUE TITLE
加载配置文件报错

### ISSUE THREAD

**Issue by whutchao** [sipt/shuttle#32]
加载配置文件报错，错误信息如下：
```
panic: Unsupported flag "2quoted" in tag "Proxy,[flow],2quoted" of type shuttle.Config [recovered]
        panic: Unsupported flag "2quoted" in tag "Proxy,[flow],2quoted" of type shuttle.Config

goroutine 1 [running]:
github.com/sipt/yaml.handleErr(0xc0001f7900)
        /Users/XXXX/Code/GoApp/src/github.com/sipt/yaml/yaml.go:249 +0x9a
panic(0xae89a0, 0xc000383aa0)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/sipt/yaml.(*decoder).mappingStruct(0xc0001a49c0, 0xc0001a16c0, 0xb69500, 0xc0001a15e0, 0x199, 0x16)
        /Users/XXXX/Code/GoApp/src/github.com/sipt/yaml/decode.go:685 +0x107c
github.com/sipt/yaml.(*decoder).mapping(0xc0001a49c0, 0xc0001a16c0, 0xb69500, 0xc0001a15e0, 0x199, 0xb69500)
        /Users/XXXX/Code/GoApp/src/github.com/sipt/yaml/decode.go:584 +0xb81
github.com/sipt/yaml.(*decoder).unmarshal(0xc0001a49c0, 0xc0001a16c0, 0xb69500, 0xc0001a15e0, 0x199, 0x1)
        /Users/XXXX/Code/GoApp/src/github.com/sipt/yaml/decode.go:332 +0x137
github.com/sipt/yaml.(*decoder).document(0xc0001a49c0, 0xc0001a1650, 0xb69500, 0xc0001a15e0, 0x199, 0xc0001f7630)
        /Users/XXXX/Code/GoApp/src/github.com/sipt/yaml/decode.go:344 +0x7a
github.com/sipt/yaml.(*decoder).unmarshal(0xc0001a49c0, 0xc0001a1650, 0xb69500, 0xc0001a15e0, 0x199, 0x199)
        /Users/XXXX/Code/GoApp/src/github.com/sipt/yaml/decode.go:320 +0x1d3
github.com/sipt/yaml.unmarshal(0xc000214000, 0x17562, 0x17762, 0xa97a40, 0xc0001a15e0, 0xb69500, 0x0, 0x0)
        /Users/XXXX/Code/GoApp/src/github.com/sipt/yaml/yaml.go:148 +0x3a1
github.com/sipt/yaml.Unmarshal(0xc000214000, 0x17562, 0x17762, 0xa97a40, 0xc0001a15e0, 0x0, 0x0)
        /Users/XXXX/Code/GoApp/src/github.com/sipt/yaml/yaml.go:81 +0x58
github.com/sipt/shuttle.InitConfig(0xbcf726, 0xc, 0xc0001f7e80, 0x4549f0, 0x40b51f)
        /Users/XXXX/Code/GoApp/src/github.com/sipt/shuttle/config.go:105 +0x199
main.main()
        /Users/XXXX/Code/GoApp/src/github.com/sipt/shuttle/cmd/main.go:29 +0x4b
```
我用的develop分支代码，MAC和Linux版本都报错，Window版本测试 。

**Comment by whutchao** [comment]
> yaml代码库
> github.com/sipt/yaml
> 请使用v2分支


我是使用的V2分支啊 。 
* v2
  remotes/origin/HEAD -> origin/v2
  remotes/origin/devel
  remotes/origin/master
  remotes/origin/rename-imports
  remotes/origin/v1
  remotes/origin/v2

**Comment by sipt** [comment]
拉一下最新代码

**Comment by whutchao** [comment]
> 拉一下`sipt/yaml` v2分支的最新代码

嗯嗯，可以了 。谢谢
